
/*
	Project WiTCHHUNT: A complete ASCII Mini RPG engine/game developed in 1.5 months!
	Copyright (C) 2007 - 2008 CCPS Solutions, Richard Marks, Rafael Hermosillo, Jeff Stagg

	This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along
	with this program; if not, write to the Free Software Foundation, Inc.,
	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

// South Jindar

// FAR_NORTHWEST_JINDAR_FOREST_S
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 9, 22, WORLD_MAP, 27, 54);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 9, 24, WORLD_MAP, 27, 54);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 9, 26, WORLD_MAP, 27, 54);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 9, 28, WORLD_MAP, 27, 54);

addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 62, 21, NORTHWEST_JINDAR_FOREST_S, 10, 29);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 62, 23, NORTHWEST_JINDAR_FOREST_S, 10, 29);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 62, 25, NORTHWEST_JINDAR_FOREST_S, 10, 29);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 62, 27, NORTHWEST_JINDAR_FOREST_S, 10, 29);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 62, 29, NORTHWEST_JINDAR_FOREST_S, 10, 29);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 62, 31, NORTHWEST_JINDAR_FOREST_S, 10, 29);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 62, 33, NORTHWEST_JINDAR_FOREST_S, 10, 29);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 62, 35, NORTHWEST_JINDAR_FOREST_S, 10, 29);

addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 29, 62, FAR_WEST_JINDAR_FOREST_S, 33, 11); 
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 31, 62, FAR_WEST_JINDAR_FOREST_S, 33, 11); 
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 33, 62, FAR_WEST_JINDAR_FOREST_S, 33, 11); 
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 35, 62, FAR_WEST_JINDAR_FOREST_S, 33, 11); 
addWarp (FAR_NORTHWEST_JINDAR_FOREST_S, 37, 62, FAR_WEST_JINDAR_FOREST_S, 33, 11); 

//=================================================

// NORTHWEST_JINDAR_FOREST_S
addWarp (NORTHWEST_JINDAR_FOREST_S, 9, 22, FAR_NORTHWEST_JINDAR_FOREST_S, 60, 29);
addWarp (NORTHWEST_JINDAR_FOREST_S, 9, 24, FAR_NORTHWEST_JINDAR_FOREST_S, 60, 29);
addWarp (NORTHWEST_JINDAR_FOREST_S, 9, 26, FAR_NORTHWEST_JINDAR_FOREST_S, 60, 29);
addWarp (NORTHWEST_JINDAR_FOREST_S, 9, 28, FAR_NORTHWEST_JINDAR_FOREST_S, 60, 29);
addWarp (NORTHWEST_JINDAR_FOREST_S, 9, 30, FAR_NORTHWEST_JINDAR_FOREST_S, 60, 29);
addWarp (NORTHWEST_JINDAR_FOREST_S, 9, 32, FAR_NORTHWEST_JINDAR_FOREST_S, 60, 29);
addWarp (NORTHWEST_JINDAR_FOREST_S, 9, 34, FAR_NORTHWEST_JINDAR_FOREST_S, 60, 29);
addWarp (NORTHWEST_JINDAR_FOREST_S, 9, 36, FAR_NORTHWEST_JINDAR_FOREST_S, 60, 29);

addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 23, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 25, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 27, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 29, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 31, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 33, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 35, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 37, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 39, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 41, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 43, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 45, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 47, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 49, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 51, NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHWEST_JINDAR_FOREST_S, 62, 53, NORTHEAST_JINDAR_FOREST_S, 11, 37);

//=================================================

// NORTHEAST_JINDAR_FOREST_S
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 23, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 25, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 27, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 29, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 31, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 33, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 35, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 37, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 39, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 41, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 43, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 45, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 47, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 49, NORTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (NORTHEAST_JINDAR_FOREST_S, 9, 51, NORTHWEST_JINDAR_FOREST_S, 60, 35);

addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 24, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 26, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 28, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 30, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 32, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 34, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 36, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 38, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 40, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 42, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 44, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 46, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);
addWarp (NORTHEAST_JINDAR_FOREST_S, 62, 48, FAR_NORTHEAST_JINDAR_FOREST_S, 11, 37);

addWarp (NORTHEAST_JINDAR_FOREST_S, 38, 62, EAST_JINDAR_FOREST_S, 40, 11);
addWarp (NORTHEAST_JINDAR_FOREST_S, 40, 62, EAST_JINDAR_FOREST_S, 40, 11);
addWarp (NORTHEAST_JINDAR_FOREST_S, 42, 62, EAST_JINDAR_FOREST_S, 40, 11);
addWarp (NORTHEAST_JINDAR_FOREST_S, 44, 62, EAST_JINDAR_FOREST_S, 40, 11);

//==================================================

// FAR_NORTHEAST_JINDAR_FOREST_S
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 24, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 26, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 28, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 30, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 32, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 34, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 36, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 38, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 40, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 42, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 44, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 46, NORTHEAST_JINDAR_FOREST_S, 60, 37);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 9, 48, NORTHEAST_JINDAR_FOREST_S, 60, 37);

addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 19, 62, FAR_EAST_JINDAR_FOREST_S, 26, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 21, 62, FAR_EAST_JINDAR_FOREST_S, 26, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 23, 62, FAR_EAST_JINDAR_FOREST_S, 26, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 25, 62, FAR_EAST_JINDAR_FOREST_S, 26, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 27, 62, FAR_EAST_JINDAR_FOREST_S, 26, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 29, 62, FAR_EAST_JINDAR_FOREST_S, 26, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_S, 31, 62, FAR_EAST_JINDAR_FOREST_S, 26, 11);

//========================================

// FAR_WEST_JINDAR_FOREST_S
addWarp (FAR_WEST_JINDAR_FOREST_S, 29, 9, FAR_NORTHWEST_JINDAR_FOREST_S, 34, 60);
addWarp (FAR_WEST_JINDAR_FOREST_S, 31, 9, FAR_NORTHWEST_JINDAR_FOREST_S, 34, 60);
addWarp (FAR_WEST_JINDAR_FOREST_S, 33, 9, FAR_NORTHWEST_JINDAR_FOREST_S, 34, 60);
addWarp (FAR_WEST_JINDAR_FOREST_S, 35, 9, FAR_NORTHWEST_JINDAR_FOREST_S, 34, 60);
addWarp (FAR_WEST_JINDAR_FOREST_S, 37, 9, FAR_NORTHWEST_JINDAR_FOREST_S, 34, 60);
addWarp (FAR_WEST_JINDAR_FOREST_S, 39, 9, FAR_NORTHWEST_JINDAR_FOREST_S, 34, 60);

addWarp (FAR_WEST_JINDAR_FOREST_S, 62, 32, WEST_JINDAR_FOREST_S, 11, 38);
addWarp (FAR_WEST_JINDAR_FOREST_S, 62, 34, WEST_JINDAR_FOREST_S, 11, 38);
addWarp (FAR_WEST_JINDAR_FOREST_S, 62, 36, WEST_JINDAR_FOREST_S, 11, 38);
addWarp (FAR_WEST_JINDAR_FOREST_S, 62, 38, WEST_JINDAR_FOREST_S, 11, 38);
addWarp (FAR_WEST_JINDAR_FOREST_S, 62, 40, WEST_JINDAR_FOREST_S, 11, 38);
addWarp (FAR_WEST_JINDAR_FOREST_S, 62, 42, WEST_JINDAR_FOREST_S, 11, 38);
addWarp (FAR_WEST_JINDAR_FOREST_S, 62, 44, WEST_JINDAR_FOREST_S, 11, 38);

//========================================

// WEST_JINDAR_FOREST_S
addWarp (WEST_JINDAR_FOREST_S, 9, 32, FAR_WEST_JINDAR_FOREST_S, 60, 38);
addWarp (WEST_JINDAR_FOREST_S, 9, 34, FAR_WEST_JINDAR_FOREST_S, 60, 38);
addWarp (WEST_JINDAR_FOREST_S, 9, 36, FAR_WEST_JINDAR_FOREST_S, 60, 38);
addWarp (WEST_JINDAR_FOREST_S, 9, 38, FAR_WEST_JINDAR_FOREST_S, 60, 38);
addWarp (WEST_JINDAR_FOREST_S, 9, 40, FAR_WEST_JINDAR_FOREST_S, 60, 38);
addWarp (WEST_JINDAR_FOREST_S, 9, 42, FAR_WEST_JINDAR_FOREST_S, 60, 38);
addWarp (WEST_JINDAR_FOREST_S, 9, 44, FAR_WEST_JINDAR_FOREST_S, 60, 38);

//=========================================

// EAST_JINDAR_FOREST_S
addWarp (EAST_JINDAR_FOREST_S, 37, 9, NORTHEAST_JINDAR_FOREST_S, 42, 61);
addWarp (EAST_JINDAR_FOREST_S, 39, 9, NORTHEAST_JINDAR_FOREST_S, 42, 61);
addWarp (EAST_JINDAR_FOREST_S, 41, 9, NORTHEAST_JINDAR_FOREST_S, 42, 61);
addWarp (EAST_JINDAR_FOREST_S, 43, 9, NORTHEAST_JINDAR_FOREST_S, 42, 61);

addWarp (EAST_JINDAR_FOREST_S, 62, 23, FAR_EAST_JINDAR_FOREST_S, 11, 31);
addWarp (EAST_JINDAR_FOREST_S, 62, 25, FAR_EAST_JINDAR_FOREST_S, 11, 31);
addWarp (EAST_JINDAR_FOREST_S, 62, 27, FAR_EAST_JINDAR_FOREST_S, 11, 31);
addWarp (EAST_JINDAR_FOREST_S, 62, 29, FAR_EAST_JINDAR_FOREST_S, 11, 31);
addWarp (EAST_JINDAR_FOREST_S, 62, 31, FAR_EAST_JINDAR_FOREST_S, 11, 31);
addWarp (EAST_JINDAR_FOREST_S, 62, 33, FAR_EAST_JINDAR_FOREST_S, 11, 31);
addWarp (EAST_JINDAR_FOREST_S, 62, 35, FAR_EAST_JINDAR_FOREST_S, 11, 31);
addWarp (EAST_JINDAR_FOREST_S, 62, 37, FAR_EAST_JINDAR_FOREST_S, 11, 31);
addWarp (EAST_JINDAR_FOREST_S, 62, 39, FAR_EAST_JINDAR_FOREST_S, 11, 31);
addWarp (EAST_JINDAR_FOREST_S, 62, 41, FAR_EAST_JINDAR_FOREST_S, 11, 31);

addWarp (EAST_JINDAR_FOREST_S, 22, 62, SOUTHEAST_JINDAR_FOREST_S, 32, 11); 
addWarp (EAST_JINDAR_FOREST_S, 24, 62, SOUTHEAST_JINDAR_FOREST_S, 32, 11); 
addWarp (EAST_JINDAR_FOREST_S, 26, 62, SOUTHEAST_JINDAR_FOREST_S, 32, 11); 
addWarp (EAST_JINDAR_FOREST_S, 28, 62, SOUTHEAST_JINDAR_FOREST_S, 32, 11); 
addWarp (EAST_JINDAR_FOREST_S, 30, 62, SOUTHEAST_JINDAR_FOREST_S, 32, 11); 
addWarp (EAST_JINDAR_FOREST_S, 32, 62, SOUTHEAST_JINDAR_FOREST_S, 32, 11); 
addWarp (EAST_JINDAR_FOREST_S, 34, 62, SOUTHEAST_JINDAR_FOREST_S, 32, 11); 
addWarp (EAST_JINDAR_FOREST_S, 36, 62, SOUTHEAST_JINDAR_FOREST_S, 32, 11); 
addWarp (EAST_JINDAR_FOREST_S, 38, 62, SOUTHEAST_JINDAR_FOREST_S, 32, 11); 
addWarp (EAST_JINDAR_FOREST_S, 40, 62, SOUTHEAST_JINDAR_FOREST_S, 32, 11);

//========================================= 

// FAR_EAST_JINDAR_FOREST_S
addWarp (FAR_EAST_JINDAR_FOREST_S, 19, 9, FAR_NORTHEAST_JINDAR_FOREST_S, 26, 60);
addWarp (FAR_EAST_JINDAR_FOREST_S, 21, 9, FAR_NORTHEAST_JINDAR_FOREST_S, 26, 60);
addWarp (FAR_EAST_JINDAR_FOREST_S, 23, 9, FAR_NORTHEAST_JINDAR_FOREST_S, 26, 60);
addWarp (FAR_EAST_JINDAR_FOREST_S, 25, 9, FAR_NORTHEAST_JINDAR_FOREST_S, 26, 60);
addWarp (FAR_EAST_JINDAR_FOREST_S, 27, 9, FAR_NORTHEAST_JINDAR_FOREST_S, 26, 60);
addWarp (FAR_EAST_JINDAR_FOREST_S, 29, 9, FAR_NORTHEAST_JINDAR_FOREST_S, 26, 60);
addWarp (FAR_EAST_JINDAR_FOREST_S, 31, 9, FAR_NORTHEAST_JINDAR_FOREST_S, 26, 60);
addWarp (FAR_EAST_JINDAR_FOREST_S, 33, 9, FAR_NORTHEAST_JINDAR_FOREST_S, 26, 60);

addWarp (FAR_EAST_JINDAR_FOREST_S, 9, 23, EAST_JINDAR_FOREST_S, 60, 33);
addWarp (FAR_EAST_JINDAR_FOREST_S, 9, 25, EAST_JINDAR_FOREST_S, 60, 33);
addWarp (FAR_EAST_JINDAR_FOREST_S, 9, 27, EAST_JINDAR_FOREST_S, 60, 33);
addWarp (FAR_EAST_JINDAR_FOREST_S, 9, 29, EAST_JINDAR_FOREST_S, 60, 33);
addWarp (FAR_EAST_JINDAR_FOREST_S, 9, 31, EAST_JINDAR_FOREST_S, 60, 33);
addWarp (FAR_EAST_JINDAR_FOREST_S, 9, 33, EAST_JINDAR_FOREST_S, 60, 33);
addWarp (FAR_EAST_JINDAR_FOREST_S, 9, 35, EAST_JINDAR_FOREST_S, 60, 33);
addWarp (FAR_EAST_JINDAR_FOREST_S, 9, 37, EAST_JINDAR_FOREST_S, 60, 33);
addWarp (FAR_EAST_JINDAR_FOREST_S, 9, 39, EAST_JINDAR_FOREST_S, 60, 33);
addWarp (FAR_EAST_JINDAR_FOREST_S, 9, 41, EAST_JINDAR_FOREST_S, 60, 33);
 
//=========================================


// FAR_SOUTHWEST_JINDAR_FOREST_S
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 22, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 24, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 26, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 28, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 30, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 32, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 34, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 36, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 38, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 40, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 42, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 44, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 46, SOUTHWEST_JINDAR_FOREST_S, 11, 30);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_S, 62, 48, SOUTHWEST_JINDAR_FOREST_S, 11, 30);


// BUGFIX
// story triggers are 1 character in size, not 4 characters square like warps
// that is what caused the malfunction!
addTrigger (createTrigger (trigger_story_5, 34, 36, FAR_SOUTHWEST_JINDAR_FOREST_S, DisableAutoOff));
addTrigger (createTrigger (trigger_story_5, 35, 36, FAR_SOUTHWEST_JINDAR_FOREST_S, DisableAutoOff));
addTrigger (createTrigger (trigger_story_5, 36, 36, FAR_SOUTHWEST_JINDAR_FOREST_S, DisableAutoOff));
addTrigger (createTrigger (trigger_story_5, 37, 36, FAR_SOUTHWEST_JINDAR_FOREST_S, DisableAutoOff));

// ========================================

// SOUTHWEST_JINDAR_FOREST_S

addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 21, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 23, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 25, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 27, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 29, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 31, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 33, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 35, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 37, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 39, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 41, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 43, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 45, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 9, 47, FAR_SOUTHWEST_JINDAR_FOREST_S, 60, 35);


addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 24, SOUTHEAST_JINDAR_FOREST_S, 11, 33);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 26, SOUTHEAST_JINDAR_FOREST_S, 11, 33);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 28, SOUTHEAST_JINDAR_FOREST_S, 11, 33);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 30, SOUTHEAST_JINDAR_FOREST_S, 11, 33);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 32, SOUTHEAST_JINDAR_FOREST_S, 11, 33);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 34, SOUTHEAST_JINDAR_FOREST_S, 11, 33);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 36, SOUTHEAST_JINDAR_FOREST_S, 11, 33);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 38, SOUTHEAST_JINDAR_FOREST_S, 11, 33);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 40, SOUTHEAST_JINDAR_FOREST_S, 11, 33);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 42, SOUTHEAST_JINDAR_FOREST_S, 11, 33);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 44, SOUTHEAST_JINDAR_FOREST_S, 11, 33);
addWarp (SOUTHWEST_JINDAR_FOREST_S, 62, 46, SOUTHEAST_JINDAR_FOREST_S, 11, 33);


// =========================================

// SOUTHEAST_JINDAR_FOREST_S
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 20, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 22, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 24, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 26, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 28, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 30, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 32, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 34, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 36, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 38, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 40, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 42, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 44, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 
addWarp (SOUTHEAST_JINDAR_FOREST_S, 9, 46, SOUTHWEST_JINDAR_FOREST_S, 60, 37); 

addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 18, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 20, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 22, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 24, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 26, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 28, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 30, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 32, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 34, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 36, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 38, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 40, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 42, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 44, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);
addWarp (SOUTHEAST_JINDAR_FOREST_S, 62, 46, FAR_SOUTHEAST_JINDAR_FOREST_S, 11, 32);

// ========================================

// FAR_SOUTHEAST_JINDAR_FOREST_S
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 19, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 21, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 23, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 25, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 27, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 29, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 31, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 33, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 35, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 37, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 39, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 41, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 43, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 45, SOUTHEAST_JINDAR_FOREST_S, 61, 32);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 9, 47, SOUTHEAST_JINDAR_FOREST_S, 61, 32);

addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 28, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 30, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 32, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 34, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 36, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 38, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 40, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 42, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 44, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 46, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 48, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 50, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 52, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 54, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 56, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 58, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 60, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_S, 62, 62, NORTHWEST_JINDAR_FOREST_SE, 11, 21);
//==================================
















// SOUTHEAST JINDAR

// NORTHWEST_JINDAR_FOREST_SE
addWarp (NORTHWEST_JINDAR_FOREST_SE, 9, 16, FAR_SOUTHEAST_JINDAR_FOREST_S, 59, 55);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 9, 18, FAR_SOUTHEAST_JINDAR_FOREST_S, 59, 55);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 9, 20, FAR_SOUTHEAST_JINDAR_FOREST_S, 59, 55);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 9, 22, FAR_SOUTHEAST_JINDAR_FOREST_S, 59, 55);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 9, 24, FAR_SOUTHEAST_JINDAR_FOREST_S, 59, 55);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 9, 26, FAR_SOUTHEAST_JINDAR_FOREST_S, 59, 55);

addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 15, NORTH_JINDAR_FOREST_SE, 11, 21);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 17, NORTH_JINDAR_FOREST_SE, 11, 21);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 19, NORTH_JINDAR_FOREST_SE, 11, 21);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 21, NORTH_JINDAR_FOREST_SE, 11, 21);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 23, NORTH_JINDAR_FOREST_SE, 11, 21);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 25, NORTH_JINDAR_FOREST_SE, 11, 21);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 27, NORTH_JINDAR_FOREST_SE, 11, 21);

addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 40, NORTH_JINDAR_FOREST_SE, 11, 49);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 42, NORTH_JINDAR_FOREST_SE, 11, 49);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 44, NORTH_JINDAR_FOREST_SE, 11, 49);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 46, NORTH_JINDAR_FOREST_SE, 11, 49);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 48, NORTH_JINDAR_FOREST_SE, 11, 49);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 50, NORTH_JINDAR_FOREST_SE, 11, 49);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 52, NORTH_JINDAR_FOREST_SE, 11, 49);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 62, 54, NORTH_JINDAR_FOREST_SE, 11, 49);


addWarp (NORTHWEST_JINDAR_FOREST_SE, 25, 62, SOUTHWEST_JINDAR_FOREST_SE, 32, 11);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 27, 62, SOUTHWEST_JINDAR_FOREST_SE, 32, 11);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 29, 62, SOUTHWEST_JINDAR_FOREST_SE, 32, 11);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 31, 62, SOUTHWEST_JINDAR_FOREST_SE, 32, 11);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 33, 62, SOUTHWEST_JINDAR_FOREST_SE, 32, 11);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 35, 62, SOUTHWEST_JINDAR_FOREST_SE, 32, 11);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 37, 62, SOUTHWEST_JINDAR_FOREST_SE, 32, 11);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 39, 62, SOUTHWEST_JINDAR_FOREST_SE, 32, 11);
addWarp (NORTHWEST_JINDAR_FOREST_SE, 41, 62, SOUTHWEST_JINDAR_FOREST_SE, 32, 11);

// ====================================================

// NORTH_JINDAR_FOREST_SE
addWarp (NORTH_JINDAR_FOREST_SE, 9, 16, NORTHWEST_JINDAR_FOREST_SE, 60, 21);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 18, NORTHWEST_JINDAR_FOREST_SE, 60, 21);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 20, NORTHWEST_JINDAR_FOREST_SE, 60, 21);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 22, NORTHWEST_JINDAR_FOREST_SE, 60, 21);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 24, NORTHWEST_JINDAR_FOREST_SE, 60, 21);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 26, NORTHWEST_JINDAR_FOREST_SE, 60, 21);

addWarp (NORTH_JINDAR_FOREST_SE, 9, 42, NORTHWEST_JINDAR_FOREST_SE, 60, 47);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 44, NORTHWEST_JINDAR_FOREST_SE, 60, 47);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 46, NORTHWEST_JINDAR_FOREST_SE, 60, 47);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 48, NORTHWEST_JINDAR_FOREST_SE, 60, 47);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 50, NORTHWEST_JINDAR_FOREST_SE, 60, 47);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 52, NORTHWEST_JINDAR_FOREST_SE, 60, 47);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 54, NORTHWEST_JINDAR_FOREST_SE, 60, 47);
addWarp (NORTH_JINDAR_FOREST_SE, 9, 56, NORTHWEST_JINDAR_FOREST_SE, 60, 47);

addWarp (NORTH_JINDAR_FOREST_SE, 62, 16, NORTHEAST_JINDAR_FOREST_SE, 11, 20);
addWarp (NORTH_JINDAR_FOREST_SE, 62, 18, NORTHEAST_JINDAR_FOREST_SE, 11, 20);
addWarp (NORTH_JINDAR_FOREST_SE, 62, 20, NORTHEAST_JINDAR_FOREST_SE, 11, 20);
addWarp (NORTH_JINDAR_FOREST_SE, 62, 22, NORTHEAST_JINDAR_FOREST_SE, 11, 20);
addWarp (NORTH_JINDAR_FOREST_SE, 62, 24, NORTHEAST_JINDAR_FOREST_SE, 11, 20);

addWarp (NORTH_JINDAR_FOREST_SE, 62, 41, NORTHEAST_JINDAR_FOREST_SE, 11, 48);
addWarp (NORTH_JINDAR_FOREST_SE, 62, 43, NORTHEAST_JINDAR_FOREST_SE, 11, 48);
addWarp (NORTH_JINDAR_FOREST_SE, 62, 45, NORTHEAST_JINDAR_FOREST_SE, 11, 48);
addWarp (NORTH_JINDAR_FOREST_SE, 62, 47, NORTHEAST_JINDAR_FOREST_SE, 11, 48);
addWarp (NORTH_JINDAR_FOREST_SE, 62, 49, NORTHEAST_JINDAR_FOREST_SE, 11, 48);
addWarp (NORTH_JINDAR_FOREST_SE, 62, 51, NORTHEAST_JINDAR_FOREST_SE, 11, 48);
addWarp (NORTH_JINDAR_FOREST_SE, 62, 53, NORTHEAST_JINDAR_FOREST_SE, 11, 48);
addWarp (NORTH_JINDAR_FOREST_SE, 62, 55, NORTHEAST_JINDAR_FOREST_SE, 11, 48);

// ====================================================

// NORTHEAST_JINDAR_FOREST_SE
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 16, NORTH_JINDAR_FOREST_SE, 60, 21);
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 18, NORTH_JINDAR_FOREST_SE, 60, 21);
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 20, NORTH_JINDAR_FOREST_SE, 60, 21);
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 22, NORTH_JINDAR_FOREST_SE, 60, 21);
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 24, NORTH_JINDAR_FOREST_SE, 60, 21);

addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 40, NORTH_JINDAR_FOREST_SE, 60, 49);
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 42, NORTH_JINDAR_FOREST_SE, 60, 49);
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 44, NORTH_JINDAR_FOREST_SE, 60, 49);
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 46, NORTH_JINDAR_FOREST_SE, 60, 49);
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 48, NORTH_JINDAR_FOREST_SE, 60, 49);
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 50, NORTH_JINDAR_FOREST_SE, 60, 49);
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 52, NORTH_JINDAR_FOREST_SE, 60, 49);
addWarp (NORTHEAST_JINDAR_FOREST_SE, 9, 54, NORTH_JINDAR_FOREST_SE, 60, 49);

// =====================================================

// SOUTHWEST_JINDAR_FOREST_SE
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 26, 9, NORTHWEST_JINDAR_FOREST_SE, 34, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 28, 9, NORTHWEST_JINDAR_FOREST_SE, 34, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 30, 9, NORTHWEST_JINDAR_FOREST_SE, 34, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 32, 9, NORTHWEST_JINDAR_FOREST_SE, 34, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 34, 9, NORTHWEST_JINDAR_FOREST_SE, 34, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 36, 9, NORTHWEST_JINDAR_FOREST_SE, 34, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 38, 9, NORTHWEST_JINDAR_FOREST_SE, 34, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 40, 9, NORTHWEST_JINDAR_FOREST_SE, 34, 60);

addWarp (SOUTHWEST_JINDAR_FOREST_SE, 62, 33, SOUTH_JINDAR_FOREST_SE, 11, 41);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 62, 35, SOUTH_JINDAR_FOREST_SE, 11, 41);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 62, 37, SOUTH_JINDAR_FOREST_SE, 11, 41);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 62, 39, SOUTH_JINDAR_FOREST_SE, 11, 41);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 62, 41, SOUTH_JINDAR_FOREST_SE, 11, 41);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 62, 43, SOUTH_JINDAR_FOREST_SE, 11, 41);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 62, 45, SOUTH_JINDAR_FOREST_SE, 11, 41);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 62, 47, SOUTH_JINDAR_FOREST_SE, 11, 41);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 62, 49, SOUTH_JINDAR_FOREST_SE, 11, 41);
addWarp (SOUTHWEST_JINDAR_FOREST_SE, 62, 51, SOUTH_JINDAR_FOREST_SE, 11, 41);

// =====================================================

// SOUTH_JINDAR_FOREST_SE
addWarp (SOUTH_JINDAR_FOREST_SE, 9, 33, SOUTHWEST_JINDAR_FOREST_SE, 60, 42);
addWarp (SOUTH_JINDAR_FOREST_SE, 9, 35, SOUTHWEST_JINDAR_FOREST_SE, 60, 42);
addWarp (SOUTH_JINDAR_FOREST_SE, 9, 37, SOUTHWEST_JINDAR_FOREST_SE, 60, 42);
addWarp (SOUTH_JINDAR_FOREST_SE, 9, 39, SOUTHWEST_JINDAR_FOREST_SE, 60, 42);
addWarp (SOUTH_JINDAR_FOREST_SE, 9, 41, SOUTHWEST_JINDAR_FOREST_SE, 60, 42);
addWarp (SOUTH_JINDAR_FOREST_SE, 9, 43, SOUTHWEST_JINDAR_FOREST_SE, 60, 42);
addWarp (SOUTH_JINDAR_FOREST_SE, 9, 45, SOUTHWEST_JINDAR_FOREST_SE, 60, 42);
addWarp (SOUTH_JINDAR_FOREST_SE, 9, 47, SOUTHWEST_JINDAR_FOREST_SE, 60, 42);
addWarp (SOUTH_JINDAR_FOREST_SE, 9, 49, SOUTHWEST_JINDAR_FOREST_SE, 60, 42);

addWarp (SOUTH_JINDAR_FOREST_SE, 62, 24, SOUTHEAST_JINDAR_FOREST_SE, 11, 29);
addWarp (SOUTH_JINDAR_FOREST_SE, 62, 26, SOUTHEAST_JINDAR_FOREST_SE, 11, 29);
addWarp (SOUTH_JINDAR_FOREST_SE, 62, 28, SOUTHEAST_JINDAR_FOREST_SE, 11, 29);
addWarp (SOUTH_JINDAR_FOREST_SE, 62, 30, SOUTHEAST_JINDAR_FOREST_SE, 11, 29);
addWarp (SOUTH_JINDAR_FOREST_SE, 62, 32, SOUTHEAST_JINDAR_FOREST_SE, 11, 29);
addWarp (SOUTH_JINDAR_FOREST_SE, 62, 34, SOUTHEAST_JINDAR_FOREST_SE, 11, 29);

// =====================================================

// SOUTHEAST_JINDAR_FOREST_SE
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 9, 24, SOUTH_JINDAR_FOREST_SE, 60, 30);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 9, 26, SOUTH_JINDAR_FOREST_SE, 60, 30);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 9, 28, SOUTH_JINDAR_FOREST_SE, 60, 30);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 9, 30, SOUTH_JINDAR_FOREST_SE, 60, 30);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 9, 32, SOUTH_JINDAR_FOREST_SE, 60, 30);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 9, 34, SOUTH_JINDAR_FOREST_SE, 60, 30);

addWarp (SOUTHEAST_JINDAR_FOREST_SE, 30, 9, FAR_SOUTH_JINDAR_FOREST_N, 32, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 32, 9, FAR_SOUTH_JINDAR_FOREST_N, 32, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 34, 9, FAR_SOUTH_JINDAR_FOREST_N, 32, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 36, 9, FAR_SOUTH_JINDAR_FOREST_N, 32, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 38, 9, FAR_SOUTH_JINDAR_FOREST_N, 32, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 40, 9, FAR_SOUTH_JINDAR_FOREST_N, 32, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 42, 9, FAR_SOUTH_JINDAR_FOREST_N, 32, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 44, 9, FAR_SOUTH_JINDAR_FOREST_N, 32, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 46, 9, FAR_SOUTH_JINDAR_FOREST_N, 32, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_SE, 48, 9, FAR_SOUTH_JINDAR_FOREST_N, 32, 60);

// ==========================================================











// NORTH_JINDAR

// FAR_NORTHWEST_JINDAR_FOREST_N

addWarp (FAR_NORTHWEST_JINDAR_FOREST_N, 62, 18, FAR_NORTH_JINDAR_FOREST_N, 10, 23);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_N, 62, 20, FAR_NORTH_JINDAR_FOREST_N, 10, 23);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_N, 62, 22, FAR_NORTH_JINDAR_FOREST_N, 10, 23);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_N, 62, 24, FAR_NORTH_JINDAR_FOREST_N, 10, 23);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_N, 62, 26, FAR_NORTH_JINDAR_FOREST_N, 10, 23);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_N, 62, 28, FAR_NORTH_JINDAR_FOREST_N, 10, 23);
addWarp (FAR_NORTHWEST_JINDAR_FOREST_N, 62, 30, FAR_NORTH_JINDAR_FOREST_N, 10, 23);

// =================================================

// FAR_NORTH_JINDAR_FOREST_N
addWarp (FAR_NORTH_JINDAR_FOREST_N, 19 , 18, FAR_NORTHWEST_JINDAR_FOREST_N, 60 , 24);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 19 , 20, FAR_NORTHWEST_JINDAR_FOREST_N, 60 , 24);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 19 , 22, FAR_NORTHWEST_JINDAR_FOREST_N, 60 , 24);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 19 , 24, FAR_NORTHWEST_JINDAR_FOREST_N, 60 , 24);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 19 , 26, FAR_NORTHWEST_JINDAR_FOREST_N, 60 , 24);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 19 , 28, FAR_NORTHWEST_JINDAR_FOREST_N, 60 , 24);

addWarp (FAR_NORTH_JINDAR_FOREST_N, 19, 9, HOLLIS, 34, 60);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 21, 9, HOLLIS, 34, 60);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 23, 9, HOLLIS, 34, 60);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 25, 9, HOLLIS, 34, 60);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 27, 9, HOLLIS, 34, 60);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 29, 9, HOLLIS, 34, 60);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 31, 9, HOLLIS, 34, 60);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 33, 9, HOLLIS, 34, 60);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 35, 9, HOLLIS, 34, 60);


addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 21, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 23, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 25, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 27, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 29, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 31, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 33, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 35, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 37, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 39, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 41, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 43, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 45, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);
addWarp (FAR_NORTH_JINDAR_FOREST_N, 62, 47, FAR_NORTHEAST_JINDAR_FOREST_N, 11, 36);

// ===================================================

// FAR_NORTHEAST_JINDAR_FOREST_N
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 23, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 25, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 27, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 29, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 31, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 33, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 35, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 37, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 39, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 41, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 43, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 45, FAR_NORTH_JINDAR_FOREST_N, 60, 35);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 9, 47, FAR_NORTH_JINDAR_FOREST_N, 60, 35);

addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 32, 62, NORTHEAST_JINDAR_FOREST_N, 40, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 34, 62, NORTHEAST_JINDAR_FOREST_N, 40, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 36, 62, NORTHEAST_JINDAR_FOREST_N, 40, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 38, 62, NORTHEAST_JINDAR_FOREST_N, 40, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 40, 62, NORTHEAST_JINDAR_FOREST_N, 40, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 42, 62, NORTHEAST_JINDAR_FOREST_N, 40, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 44, 62, NORTHEAST_JINDAR_FOREST_N, 40, 11);
addWarp (FAR_NORTHEAST_JINDAR_FOREST_N, 46, 62, NORTHEAST_JINDAR_FOREST_N, 40, 11);

// ===================================================

// NORTHWEST_JINDAR_FOREST_N
addWarp (NORTHWEST_JINDAR_FOREST_N, 62, 20, NORTH_JINDAR_FOREST_N, 11, 23);
addWarp (NORTHWEST_JINDAR_FOREST_N, 62, 22, NORTH_JINDAR_FOREST_N, 11, 23);
addWarp (NORTHWEST_JINDAR_FOREST_N, 62, 24, NORTH_JINDAR_FOREST_N, 11, 23);
addWarp (NORTHWEST_JINDAR_FOREST_N, 62, 26, NORTH_JINDAR_FOREST_N, 11, 23);
addWarp (NORTHWEST_JINDAR_FOREST_N, 62, 28, NORTH_JINDAR_FOREST_N, 11, 23);
addWarp (NORTHWEST_JINDAR_FOREST_N, 62, 30, NORTH_JINDAR_FOREST_N, 11, 23);

addWarp (NORTHWEST_JINDAR_FOREST_N, 62, 48, NORTH_JINDAR_FOREST_N, 11, 53);
addWarp (NORTHWEST_JINDAR_FOREST_N, 62, 50, NORTH_JINDAR_FOREST_N, 11, 53);
addWarp (NORTHWEST_JINDAR_FOREST_N, 62, 52, NORTH_JINDAR_FOREST_N, 11, 53);
addWarp (NORTHWEST_JINDAR_FOREST_N, 62, 54, NORTH_JINDAR_FOREST_N, 11, 53);
addWarp (NORTHWEST_JINDAR_FOREST_N, 62, 56, NORTH_JINDAR_FOREST_N, 11, 53);

addWarp (NORTHWEST_JINDAR_FOREST_N, 18, 62, SOUTHWEST_JINDAR_FOREST_N, 23, 11);
addWarp (NORTHWEST_JINDAR_FOREST_N, 20, 62, SOUTHWEST_JINDAR_FOREST_N, 23, 11);
addWarp (NORTHWEST_JINDAR_FOREST_N, 22, 62, SOUTHWEST_JINDAR_FOREST_N, 23, 11);
addWarp (NORTHWEST_JINDAR_FOREST_N, 24, 62, SOUTHWEST_JINDAR_FOREST_N, 23, 11);
addWarp (NORTHWEST_JINDAR_FOREST_N, 26, 62, SOUTHWEST_JINDAR_FOREST_N, 23, 11);

addWarp (NORTHWEST_JINDAR_FOREST_N, 46, 62, SOUTHWEST_JINDAR_FOREST_N, 49, 11);
addWarp (NORTHWEST_JINDAR_FOREST_N, 48, 62, SOUTHWEST_JINDAR_FOREST_N, 49, 11);
addWarp (NORTHWEST_JINDAR_FOREST_N, 50, 62, SOUTHWEST_JINDAR_FOREST_N, 49, 11);
addWarp (NORTHWEST_JINDAR_FOREST_N, 52, 62, SOUTHWEST_JINDAR_FOREST_N, 49, 11);
addWarp (NORTHWEST_JINDAR_FOREST_N, 54, 62, SOUTHWEST_JINDAR_FOREST_N, 49, 11);

// ===================================================

// NORTH_JINDAR_FOREST_N
addWarp (NORTH_JINDAR_FOREST_N, 9, 17, NORTHWEST_JINDAR_FOREST_N, 60, 25);
addWarp (NORTH_JINDAR_FOREST_N, 9, 19, NORTHWEST_JINDAR_FOREST_N, 60, 25);
addWarp (NORTH_JINDAR_FOREST_N, 9, 21, NORTHWEST_JINDAR_FOREST_N, 60, 25);
addWarp (NORTH_JINDAR_FOREST_N, 9, 23, NORTHWEST_JINDAR_FOREST_N, 60, 25);
addWarp (NORTH_JINDAR_FOREST_N, 9, 25, NORTHWEST_JINDAR_FOREST_N, 60, 25);
addWarp (NORTH_JINDAR_FOREST_N, 9, 27, NORTHWEST_JINDAR_FOREST_N, 60, 25);
addWarp (NORTH_JINDAR_FOREST_N, 9, 29, NORTHWEST_JINDAR_FOREST_N, 60, 25);

addWarp (NORTH_JINDAR_FOREST_N, 9, 48, NORTHWEST_JINDAR_FOREST_N, 60, 53);
addWarp (NORTH_JINDAR_FOREST_N, 9, 50, NORTHWEST_JINDAR_FOREST_N, 60, 53);
addWarp (NORTH_JINDAR_FOREST_N, 9, 52, NORTHWEST_JINDAR_FOREST_N, 60, 53);
addWarp (NORTH_JINDAR_FOREST_N, 9, 54, NORTHWEST_JINDAR_FOREST_N, 60, 53);
addWarp (NORTH_JINDAR_FOREST_N, 9, 56, NORTHWEST_JINDAR_FOREST_N, 60, 53);

addWarp (NORTH_JINDAR_FOREST_N, 15, 62, SOUTH_JINDAR_FOREST_N, 22, 11);
addWarp (NORTH_JINDAR_FOREST_N, 17, 62, SOUTH_JINDAR_FOREST_N, 22, 11);
addWarp (NORTH_JINDAR_FOREST_N, 19, 62, SOUTH_JINDAR_FOREST_N, 22, 11);

addWarp (NORTH_JINDAR_FOREST_N, 48, 62, SOUTH_JINDAR_FOREST_N, 50, 11);
addWarp (NORTH_JINDAR_FOREST_N, 50, 62, SOUTH_JINDAR_FOREST_N, 50, 11);
addWarp (NORTH_JINDAR_FOREST_N, 52, 62, SOUTH_JINDAR_FOREST_N, 50, 11);
addWarp (NORTH_JINDAR_FOREST_N, 54, 62, SOUTH_JINDAR_FOREST_N, 50, 11);

// ====================================================

// NORTHEAST_JINDAR_FOREST_N
addWarp (NORTHEAST_JINDAR_FOREST_N, 32, 9, FAR_NORTHEAST_JINDAR_FOREST_N, 40, 60);
addWarp (NORTHEAST_JINDAR_FOREST_N, 34, 9, FAR_NORTHEAST_JINDAR_FOREST_N, 40, 60);
addWarp (NORTHEAST_JINDAR_FOREST_N, 36, 9, FAR_NORTHEAST_JINDAR_FOREST_N, 40, 60);
addWarp (NORTHEAST_JINDAR_FOREST_N, 38, 9, FAR_NORTHEAST_JINDAR_FOREST_N, 40, 60);
addWarp (NORTHEAST_JINDAR_FOREST_N, 40, 9, FAR_NORTHEAST_JINDAR_FOREST_N, 40, 60);
addWarp (NORTHEAST_JINDAR_FOREST_N, 42, 9, FAR_NORTHEAST_JINDAR_FOREST_N, 40, 60);
addWarp (NORTHEAST_JINDAR_FOREST_N, 44, 9, FAR_NORTHEAST_JINDAR_FOREST_N, 40, 60);
addWarp (NORTHEAST_JINDAR_FOREST_N, 46, 9, FAR_NORTHEAST_JINDAR_FOREST_N, 40, 60);

addWarp (NORTHEAST_JINDAR_FOREST_N, 36, 62, SOUTHEAST_JINDAR_FOREST_N, 42, 11);
addWarp (NORTHEAST_JINDAR_FOREST_N, 38, 62, SOUTHEAST_JINDAR_FOREST_N, 42, 11);
addWarp (NORTHEAST_JINDAR_FOREST_N, 40, 62, SOUTHEAST_JINDAR_FOREST_N, 42, 11);
addWarp (NORTHEAST_JINDAR_FOREST_N, 42, 62, SOUTHEAST_JINDAR_FOREST_N, 42, 11);
addWarp (NORTHEAST_JINDAR_FOREST_N, 44, 62, SOUTHEAST_JINDAR_FOREST_N, 42, 11);
addWarp (NORTHEAST_JINDAR_FOREST_N, 46, 62, SOUTHEAST_JINDAR_FOREST_N, 42, 11);
addWarp (NORTHEAST_JINDAR_FOREST_N, 48, 62, SOUTHEAST_JINDAR_FOREST_N, 42, 11);

// ====================================================

// SOUTHWEST_JINDAR_FOREST_N
addWarp (SOUTHWEST_JINDAR_FOREST_N, 19, 9, NORTHWEST_JINDAR_FOREST_N, 22, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 21, 9, NORTHWEST_JINDAR_FOREST_N, 22, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 23, 9, NORTHWEST_JINDAR_FOREST_N, 22, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 25, 9, NORTHWEST_JINDAR_FOREST_N, 22, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 27, 9, NORTHWEST_JINDAR_FOREST_N, 22, 60);

addWarp (SOUTHWEST_JINDAR_FOREST_N, 46, 9, NORTHWEST_JINDAR_FOREST_N, 50, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 48, 9, NORTHWEST_JINDAR_FOREST_N, 50, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 50, 9, NORTHWEST_JINDAR_FOREST_N, 50, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 52, 9, NORTHWEST_JINDAR_FOREST_N, 50, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 54, 9, NORTHWEST_JINDAR_FOREST_N, 50, 60);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 56, 9, NORTHWEST_JINDAR_FOREST_N, 50, 60);

addWarp (SOUTHWEST_JINDAR_FOREST_N, 21, 62, FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 11);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 23, 62, FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 11);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 25, 62, FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 11);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 27, 62, FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 11);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 29, 62, FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 11);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 31, 62, FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 11);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 33, 62, FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 11);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 35, 62, FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 11);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 37, 62, FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 11);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 39, 62, FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 11);
addWarp (SOUTHWEST_JINDAR_FOREST_N, 41, 62, FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 11);

// =====================================================

// SOUTH_JINDAR_FOREST_N
addWarp (SOUTH_JINDAR_FOREST_N, 15, 9, NORTH_JINDAR_FOREST_N, 17, 60);
addWarp (SOUTH_JINDAR_FOREST_N, 17, 9, NORTH_JINDAR_FOREST_N, 17, 60);
addWarp (SOUTH_JINDAR_FOREST_N, 19, 9, NORTH_JINDAR_FOREST_N, 17, 60);
addWarp (SOUTH_JINDAR_FOREST_N, 21, 9, NORTH_JINDAR_FOREST_N, 17, 60);
addWarp (SOUTH_JINDAR_FOREST_N, 23, 9, NORTH_JINDAR_FOREST_N, 17, 60);
addWarp (SOUTH_JINDAR_FOREST_N, 25, 9, NORTH_JINDAR_FOREST_N, 17, 60);
addWarp (SOUTH_JINDAR_FOREST_N, 27, 9, NORTH_JINDAR_FOREST_N, 17, 60);

addWarp (SOUTH_JINDAR_FOREST_N, 47, 9, NORTH_JINDAR_FOREST_N, 51, 60);
addWarp (SOUTH_JINDAR_FOREST_N, 49, 9, NORTH_JINDAR_FOREST_N, 51, 60);
addWarp (SOUTH_JINDAR_FOREST_N, 51, 9, NORTH_JINDAR_FOREST_N, 51, 60);
addWarp (SOUTH_JINDAR_FOREST_N, 53, 9, NORTH_JINDAR_FOREST_N, 51, 60);

addWarp (SOUTH_JINDAR_FOREST_N, 62, 48, SOUTHEAST_JINDAR_FOREST_N, 11, 49);
addWarp (SOUTH_JINDAR_FOREST_N, 62, 50, SOUTHEAST_JINDAR_FOREST_N, 11, 49);
addWarp (SOUTH_JINDAR_FOREST_N, 62, 52, SOUTHEAST_JINDAR_FOREST_N, 11, 49);
addWarp (SOUTH_JINDAR_FOREST_N, 62, 54, SOUTHEAST_JINDAR_FOREST_N, 11, 49);
addWarp (SOUTH_JINDAR_FOREST_N, 62, 56, SOUTHEAST_JINDAR_FOREST_N, 11, 49);

// ======================================================

// SOUTHEAST_JINDAR_FOREST_N
addWarp (SOUTHEAST_JINDAR_FOREST_N, 9, 43, SOUTH_JINDAR_FOREST_N, 60, 53);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 9, 45, SOUTH_JINDAR_FOREST_N, 60, 53);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 9, 47, SOUTH_JINDAR_FOREST_N, 60, 53);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 9, 49, SOUTH_JINDAR_FOREST_N, 60, 53);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 9, 51, SOUTH_JINDAR_FOREST_N, 60, 53);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 9, 53, SOUTH_JINDAR_FOREST_N, 60, 53);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 9, 55, SOUTH_JINDAR_FOREST_N, 60, 53);

addWarp (SOUTHEAST_JINDAR_FOREST_N, 36, 9, NORTHEAST_JINDAR_FOREST_N, 42, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 38, 9, NORTHEAST_JINDAR_FOREST_N, 42, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 40, 9, NORTHEAST_JINDAR_FOREST_N, 42, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 42, 9, NORTHEAST_JINDAR_FOREST_N, 42, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 44, 9, NORTHEAST_JINDAR_FOREST_N, 42, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 46, 9, NORTHEAST_JINDAR_FOREST_N, 42, 60);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 48, 9, NORTHEAST_JINDAR_FOREST_N, 42, 60);

addWarp (SOUTHEAST_JINDAR_FOREST_N, 31, 62, FAR_SOUTHEAST_JINDAR_FOREST_N, 35, 11);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 33, 62, FAR_SOUTHEAST_JINDAR_FOREST_N, 35, 11);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 35, 62, FAR_SOUTHEAST_JINDAR_FOREST_N, 35, 11);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 37, 62, FAR_SOUTHEAST_JINDAR_FOREST_N, 35, 11);
addWarp (SOUTHEAST_JINDAR_FOREST_N, 39, 62, FAR_SOUTHEAST_JINDAR_FOREST_N, 35, 11);

// =====================================================

// FAR_SOUTHWEST_JINDAR_FOREST_N
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 21, 9, SOUTHWEST_JINDAR_FOREST_N, 31, 60);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 23, 9, SOUTHWEST_JINDAR_FOREST_N, 31, 60);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 25, 9, SOUTHWEST_JINDAR_FOREST_N, 31, 60);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 27, 9, SOUTHWEST_JINDAR_FOREST_N, 31, 60);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 29, 9, SOUTHWEST_JINDAR_FOREST_N, 31, 60);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 9, SOUTHWEST_JINDAR_FOREST_N, 31, 60);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 33, 9, SOUTHWEST_JINDAR_FOREST_N, 31, 60);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 35, 9, SOUTHWEST_JINDAR_FOREST_N, 31, 60);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 37, 9, SOUTHWEST_JINDAR_FOREST_N, 31, 60);

addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 29, 62, FAR_SOUTH_JINDAR_FOREST_N, 11, 34);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 31, 62, FAR_SOUTH_JINDAR_FOREST_N, 11, 34);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 33, 62, FAR_SOUTH_JINDAR_FOREST_N, 11, 34);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 35, 62, FAR_SOUTH_JINDAR_FOREST_N, 11, 34);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 37, 62, FAR_SOUTH_JINDAR_FOREST_N, 11, 34);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 39, 62, FAR_SOUTH_JINDAR_FOREST_N, 11, 34);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 41, 62, FAR_SOUTH_JINDAR_FOREST_N, 11, 34);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 43, 62, FAR_SOUTH_JINDAR_FOREST_N, 11, 34);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 45, 62, FAR_SOUTH_JINDAR_FOREST_N, 11, 34);
addWarp (FAR_SOUTHWEST_JINDAR_FOREST_N, 47, 62, FAR_SOUTH_JINDAR_FOREST_N, 11, 34);

// =====================================================

// FAR_SOUTH_JINDAR_FOREST_N
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 20, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 22, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 24, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 26, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 28, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 30, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 32, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 34, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 36, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 38, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 40, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 42, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 44, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 46, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 9, 48, FAR_SOUTHWEST_JINDAR_FOREST_N, 38, 60);

addWarp (FAR_SOUTH_JINDAR_FOREST_N, 21, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 23, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 25, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 27, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 29, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 31, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 33, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 35, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 37, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 39, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 41, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 43, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);
addWarp (FAR_SOUTH_JINDAR_FOREST_N, 45, 62, SOUTHEAST_JINDAR_FOREST_SE, 39, 10);

// =====================================================

// FAR_SOUTHEAST_JINDAR_FOREST_N
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_N, 29, 9, SOUTHEAST_JINDAR_FOREST_N, 36, 60);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_N, 31, 9, SOUTHEAST_JINDAR_FOREST_N, 36, 60);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_N, 33, 9, SOUTHEAST_JINDAR_FOREST_N, 36, 60);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_N, 35, 9, SOUTHEAST_JINDAR_FOREST_N, 36, 60);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_N, 37, 9, SOUTHEAST_JINDAR_FOREST_N, 36, 60);
addWarp (FAR_SOUTHEAST_JINDAR_FOREST_N, 39, 9, SOUTHEAST_JINDAR_FOREST_N, 36, 60);

addTrigger (createTrigger (trigger_restoration, 26, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 27, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 28, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 29, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 30, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 31, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 32, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 33, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 34, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 35, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 36, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 37, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 38, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 39, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 40, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 41, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 42, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 43, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 44, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 45, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 46, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 47, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));
addTrigger (createTrigger (trigger_restoration, 48, 43, FAR_SOUTHEAST_JINDAR_FOREST_N, DisableAutoOff));

// ====================================================
